import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--rank', type=int, default=0)
parser.add_argument('--world_size', type=int, default=3)
parser.add_argument('--adj_matrix', type=str, default='adj_matrix.npy')
parser.add_argument('--is_Server', type=bool, default=True)
parser.add_argument('--backend', type=str, default='gloo')
parser.add_argument('--net', type=str, default='enp4s0')
parser.add_argument('--epochs', type=int, default=1)
parser.add_argument('--lam', type=float, default=0.001)
parser.add_argument('--error', type=float, default=1e-2)
parser.add_argument('--local_lr', type=float, default=1e-2)
parser.add_argument('--global_lr', type=float, default=1e-3 )
args = parser.parse_args()